<?php

namespace AppBundle\Repository;

/**
 * majetekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class majetekRepository extends \Doctrine\ORM\EntityRepository
{
}
