<?php

namespace AppBundle\Repository;

/**
 * majitelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class majitelRepository extends \Doctrine\ORM\EntityRepository
{
}
