<?php

namespace AppBundle\Repository;

/**
 * playersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class playersRepository extends \Doctrine\ORM\EntityRepository
{
}
