<?php

namespace AppBundle\Repository;

/**
 * skladRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class skladRepository extends \Doctrine\ORM\EntityRepository
{
}
