<?php

namespace AppBundle\Repository;

/**
 * teamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class teamsRepository extends \Doctrine\ORM\EntityRepository
{
}
